---
abstract: 'Manage loading, accessing, updating one or more sequences of data for statistical analysis'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Array::Compare: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Data
provides:
  Statistics::Data:
    file: lib/Statistics/Data.pm
    version: 0.04
requires:
  Data::Serializer: 0.59
  List::AllUtils: 0.03
  Scalar::Util: 1.23
  String::Util: 0.11
  Text::SimpleTable: 2.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
