---
abstract: 'Load, access, update, check and save one or more sequences of data for statistical analysis'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Array::Compare: 2.02
  Test::More: 0.92
configure_requires:
  Module::Build: 0.4007
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Data
provides:
  Statistics::Data:
    file: lib/Statistics/Data.pm
    version: 0.08
requires:
  Data::Serializer: 0.59
  List::AllUtils: 0.03
  Number::Misc: 1.0
  Scalar::Util: 1.27
  String::Util: 0.21
  Text::SimpleTable: 2.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
