---
abstract: 'Manage loading, reading, updating, storing, etc. one or more sequences of data for statistical analysis'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Data
provides:
  Statistics::Data:
    file: lib/Statistics/Data.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
